#!/bin/bash
export PYTHONPATH=$HOME/projects/StravaAwards:$PYTHONPATH
export FLASK_DEBUG=0
export FLASK_APP=__init__.py
export ENVIROMENT=development
echo "running flask"
gunicorn  --workers=2 --log-level debug  wsgi
#flask run
